[build]
base = "."
command = "npm run build"
publish = "dist"
ignoreSubmodules = true

[build.environment]
NODE_VERSION = "20.14.0"  # Current LTS
NPM_VERSION = "10.7.0"
NODE_OPTIONS = "--max_old_space_size=4096"

[functions]
node_bundler = "esbuild"

# [[plugins]]
#   package = "@netlify/plugin-nextjs"
